name: Deploy Backend to Railway

on:
  push:
    branches:
      - main # أو الفرع اللي حابب ترفعه تلقائيًا

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ① سحب الكود من المستودع
      - name: Checkout Code
        uses: actions/checkout@v4

      # ② إعداد Node.js (لو تطبيق Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # حدد إصدار Node الخاص بمشروعك

      # ③ تثبيت الـ Dependencies
      - name: Install Dependencies
        run: npm install

      # ④ تشغيل الاختبارات (اختياري)
      # - name: Run Tests
      #   run: npm test

      # ⑤ النشر إلى Railway
      - name: Deploy to Railway
        run: |
          npm install -g @railway/cli
          railway up --service YOUR_SERVICE_NAME
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
